name: "example"
on: [push]
jobs:
  publish:
    name: Example Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Publish
        uses: ./
        with:
          machine_key: ${{ secrets.MACHINE_KEY }}
          remote: staging
          workdir: ./example
          app_url: publish.fissionapp.net
          verbose: true
